version: '3'

services:
  photo-frame:
    image: amcolash/google-photo-frame
    container_name: google-photo-frame
    build: ./
    network_mode: 'host'
    volumes:
      - ./settings.json:/usr/src/app/settings.json
      - ./tmp:/usr/src/app/tmp
    entrypoint: npm run docker
    env_file:
      - .env
    restart: unless-stopped
