version: '3'

services:
  photo-frame:
    image: amcolash/photo-frame
    container_name: photo-frame
    build: ./
    network_mode: 'host'
    volumes:
      - ./settings.json:/usr/src/app/settings.json
    entrypoint: npm run docker
    env_file:
      - .env
    restart: unless-stopped
